{{- if .Values.sftp.enabled }}
{{- with $serviceSpec := .Values.sftp.service }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "craftycontroller.fullname" $ }}-sftp
  labels:
    {{- include "craftycontroller.labels" $ | nindent 4 }}
    {{- with $serviceSpec.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $serviceSpec.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $serviceSpec.type }}
  ports:
    {{- list $serviceSpec.port | toYaml | nindent 4 }}
  selector:
    {{- include "craftycontroller.selectorLabels" $ | nindent 4 }}
  {{- with $serviceSpec.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sftp-scripts
data:
  copy-certs.sh: |
    cp -Lr /etc/ssh-keys/* /etc/ssh/
    chmod 600 /etc/ssh/ssh_host*
{{- end }}
