## Reference: https://github.com/helm/chart-testing-action
name: Postgrescluster Watcher
on:
  schedule:
    - cron: "0 23 * * 5" # Every Friday night
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Clone CrunchyData/postgres-operator-examples
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          owner: CrunchyData
          repository: postgres-operator-examples

      - name: Copy postgrescluster chart
        run: |
          cp -r postgres-operator-examples/helm/postgres/* ./charts/postgrescluster/
          rm -rf postgres-operator-examples

      - name: Check if there are changes
        id: changes
        uses: UnicornGlobal/has-changes-action@v1.0.11

      - name: Commit and open pull request
        if: steps.changes.outputs.changed == 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd helm-charts
          export CHART_VERSION=$(cat charts/postgrescluster/Chart.yaml | grep ^version | cut -d ' ' -f 2)
          git checkout "postgrescluster-$CHART_VERSION"
          git add .
          git commit -m "Upgrade postgrescluster to $CHART_VERSION"
          git push
          gh pr create --fill
